[config]
default_to_workspace = false
min_version = "0.36.9"

[tasks.format-rust]
args = ["fmt"]
command = "cargo"
dependencies = ["install-rustfmt"]

[tasks.lint-rust-format]
args = ["fmt", "--all", "--", "--check"]
command = "cargo"
dependencies = ["install-rustfmt"]

[tasks.lint-rust]
args = [
  "clippy",
  "--workspace",
  "--locked",
  "--all-targets",
  "--",
  "-D",
  "clippy::all",
  "-D",
  "warnings",
]
command = "cargo"
dependencies = ["install-clippy"]

[tasks.lint-toml]
args = ["lint"]
command = "taplo"
dependencies = ["install-taplo-cli"]

[tasks.format-toml]
args = ["fmt"]
command = "taplo"
dependencies = ["install-taplo-cli"]

[tasks.lint]
dependencies = ["lint-rust-format", "lint-rust", "lint-toml"]

[tasks.format]
dependencies = ["format-rust", "format-toml"]

[tasks.backend-build]
args = ["build"]
command = "cargo"
cwd = "./backend/"

[tasks.backend-start]
dependencies = ["backend-build"]
args = ["run"]
command = "cargo"
cwd = "./backend/"

[tasks.backend-dev]
args = ["watch", "-x", "run"]
command = "cargo"
cwd = "./backend/"

[tasks.client-build]
args = ["build"]
command = "trunk"
cwd = "./client/"

[tasks.client-start]
dependencies = ["client-build"]
args = ["serve"]
command = "trunk"
cwd = "./client/"

[tasks.install-clippy]
install_crate = { rustup_component_name = "clippy" }

[tasks.install-rustfmt]
install_crate = { rustup_component_name = "rustfmt" }

[tasks.install-taplo-cli]
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = "--help" }
